### ISSUE TITLE
Pagination does not work in categories and tags

### ISSUE THREAD

**Issue by jorgesumle** [MinchinWeb/blog.minchin.ca#6]
When I am in the page of a category or tag, pagination leads me to a non-existing page and I get a 404 error.

For example, when I'm in http://blog.minchin.ca/label/python/ and click on the 2 page, I get to http://blog.minchin.ca/label/python/2.html, which doesn't exists.

The same problem with categories. For instance: http://blog.minchin.ca/category/misc/4.html

**Comment by MinchinWeb** [comment]
Great catch! I guess I've haven't clicked on those links in a while. The [fix](https://github.com/MinchinWeb/seafoam/commit/3a16503d6c2450d947cfb55b3f204d075bdaafd7) was included in Seafoam 2.1.1 (released today) and the blog has been re-rendered.
